In [1]:
import tensorflow as tf

# Problem D.1 - Autodifferentiation of $f(w_0, w_1) = w_0 + w_1^2$
<br>
Here the task is to achieve differentiation of $f(w_0, w_1) = w_0 + w_1^2$ using Tensorflow2.
<br>
Confirm that this results in the following output, which shows that the desired gradient is
the vector $[1.0, 8.0]^T$ .

In [2]:
# Define function h1 to differentiate.
def h1(w):
    return w[0] + w[1] ** 2

# In analogy with numpy arrays, create a Tensorflow2 tensor called tf_w.
tf_w = tf.Variable([3.0,4.0])

# Perform the gradient calculation by means of the GradientTape functionality.
with tf.GradientTape() as tape:
    tf_z1 = h1(tf_w)

grad_h1 = tape.gradient(tf_z1, tf_w)

grad_h1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 8.], dtype=float32)>

Now rewrite the function h1 by means of a for-loop instead, and call the new function h2.
<br>
Thus the only difference here is that h2 is implemented by means of a for-loop:

In [3]:
# Define function h2 to differentiate.
def h2(w):
    s = 0
    for i in range(2):
        s = s + w[i] ** (i + 1)
    return s

Finally perform the gradient calculations again, this time for h2:

In [4]:
# In analogy with numpy arrays, create a Tensorflow2 tensor called tf_w.
tf_w = tf.Variable([3.0,4.0])

with tf.GradientTape() as tape:
    tf_z2 = h2(tf_w)
    
grad_h2 = tape.gradient(tf_z2, tf_w)

grad_h2

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 8.], dtype=float32)>

Confirm that you get the same gradient as for h1.

In [5]:
import torch
print("Using torch", torch.__version__)

Using torch 1.9.0


In [6]:
torch.manual_seed(13)

In [7]:
data = [1, 2, 3, 4, 5]
first_tensor = torch.tensor(data)

first_tensor

tensor([1, 2, 3, 4, 5])

In [8]:
data = [[0, 1],
        [2, 3], 
        [4, 5]
       ]

second_tensor = torch.tensor(data)

second_tensor

tensor([[0, 1],
        [2, 3],
        [4, 5]])