# Problem 1
<br>
Run and explain what the code does and why.

In [ ]:
import numpy as np

# Generate 10 training examples and a constant add bias to the X matrix
N = 10

# y = 4x + 3
# True values of a and b
a_true = 4.0
b_true = 3.0

# Create 10 random x value
X = 2 * np.random.rand(N, 1)
# Calculate the real y value according to the x values created above
y = a_true * X + b_true

# Add x0 = 1 to each instance as first column
X_b = np.column_stack([np.ones((N, 1)), X]) 

eta = 0.1   # learning rate
n_iterations = 300

# Initial guess
a0 = 1.0
b0 = 1.0
w = np.array([[b0], [a0]])

# Gradient Decent update
for iteration in range(n_iterations):
    # Calculate the gradient of J(w; D)
    grad = 2 / N * X_b.T.dot(X_b.dot(w) - y)
    # update w
    w = w - eta * grad

w_from_np = w
print(w_from_np)

[[3.00003797]
 [3.99996441]]


# Problem 2
<br>
Run and explain what the code does and why.

In [ ]:
import tensorflow as tf

N = 10

# True values of a and b
a_true = 4.0
b_true = 3.0

# Generate 10 training examples and a constant add bias to the X matrix
X = 2 * np.random.rand(N, 1)
# Calculate the real y value according to the x values created above
y = a_true * X + b_true
# Add x0 = 1 to each instance as first column
X_b = np.column_stack([np.ones((N, 1)), X]) 

# Convert from numpy to tensorflow variables
tf_X_b = tf.convert_to_tensor(X_b, dtype = tf.float64)
tf_y = tf.convert_to_tensor(y, dtype = tf.float64)

# Build an in house mean squared error function called mse_inhouse
def mse_inhouse(*args):
    tf_w = args[0]
    tf_X_b = args[1]
    tf_y = args[2]
    # Matrix multiplication
    tf_y_hat = tf.matmul(tf_X_b, tf_w)
    # 
    tf_mse = tf.math.reduce_mean((tf_y_hat - tf_y) ** 2)
    return tf_mse

eta = 0.1 # Learning rate
# Set iteration times
n_iterations = 300

# Initial guess: a0 = 0, b0 = 0
w_random = np.array([[b0], [a0]])
# Convert initial guess to TF variable
tf_w = tf.convert_to_tensor(w_random, dtype = tf.float64) 

for iteration in range(n_iterations):
    with tf.GradientTape() as tape:
        tape.watch(tf_w)
        tf_mse = mse_inhouse(tf_w, tf_X_b, tf_y)
        grad_mse_inhouse = tape.gradient(tf_mse, tf_w)
        tf_w = tf_w - eta * grad_mse_inhouse

# Tensorflow2 allows direct conversion like this
w_from_tf = np.array(tf_w) 
print(w_from_tf)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[3.0042435 ],
       [3.99669267]])>

# Problem 3
<br>
Run and explain what the code does and why.

In [1]:
import torch
from torch import autograd

# Generate 10 training examples
N = 10
# True values of a and b
a_true = 4.0
b_true = 3.0

# Generate 10 training examples
X = 2 * torch.randn(N, 1)
# Calculate the real y value according to the x values created above
y_obs = a_true * X + b_true

# y = a * x + b
def my_linear_model(X, w):
    a = w[0]
    b = w[1]
    return a * X + b

# The loss function, J = (y_true - y_pred) ^ 2
def my_l2_loss_function(y_pred, y_true):
    return torch.pow(y_true - y_pred, 2.0)

# The cost function
def my_cost_function(y_pred, y_true):
    loss_over_data = my_l2_loss_function(y_pred, y_true)
    return torch.mean(loss_over_data)

# Learning rate aka step-size
eta = 0.01 
# Nr. GD iterations
n_iterations = 300 
# Param Initialization
w_pt = torch.randn(size=[2], requires_grad = True) 

for iteration_i in range(n_iterations):
    y_preds = my_linear_model(X, w_pt)
    cost = my_cost_function(y_preds, y_obs)
    cost.backward()
    
    with torch.no_grad():
        w_pt -= eta * w_pt.grad
    w_pt.grad.zero_()

w_from_PyTorch = w_pt.detach().numpy()
w_from_PyTorch

array([4.0053163, 2.9747663], dtype=float32)

# Problem 4
<br>
Compare the results from Problems 1-3 above with each other and with the model $y = 4x + 3$ used to generate the data. Do the results agree?
<br>
Answer: The results agree.